# Generated by Django 4.2.14 on 2024-10-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
